[package]
name = "mrkirdid/kmdr"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "A strictly-typed, modern command console for Roblox. Reimagined fork of evaera's Cmdr."
exclude = [
	"Packages",
	"Packages/**",
	"test",
	"test/**",
	"dev.project.json",
	"rokit.toml",
	"selene.toml",
	"sourcemap.json",
	"wally.lock",
	"DESIGN.md",
	"KmdrDev.rbxl",
	"KmdrDev.rbxl.lock",
	"*.rbxl",
	"*.rbxl.lock",
]

[dependencies]
Fusion = "elttob/fusion@0.3.0"
