return {
	["Tie Guy"] = {
		Value = 1,
		Rarity = 1 / 2,
	},

	["File Folder"] = {
		Value = 1.3,
		Rarity = 1 / 3,
	},

	LightBulb = {
		Value = 1.6,
		Rarity = 1 / 5,
	},

	MegaPhone = {
		Value = 2,
		Rarity = 1 / 8,
	},

	Corny = {
		Value = 2.4,
		Rarity = 1 / 12,
	},

	Carrot = {
		Value = 2.9,
		Rarity = 1 / 18,
	},

	Banana = {
		Value = 3.4,
		Rarity = 1 / 28,
	},

	Cupcake = {
		Value = 3.9,
		Rarity = 1 / 45,
	},

	Toasty = {
		Value = 4.4,
		Rarity = 1 / 70,
	},

	Hamster = {
		Value = 5,
		Rarity = 1 / 110,
	},

	SnowMan = {
		Value = 5.5,
		Rarity = 1 / 170,
	},

	ClockWork = {
		Value = 6,
		Rarity = 1 / 260,
	},

	["TV Head"] = {
		Value = 6.5,
		Rarity = 1 / 400,
	},

	["Dino Guy"] = {
		Value = 7,
		Rarity = 1 / 600,
	},

	Robot = {
		Value = 7.5,
		Rarity = 1 / 900,
	},

	Spaceman = {
		Value = 8,
		Rarity = 1 / 1_400,
	},

	Minotaur = {
		Value = 8.4,
		Rarity = 1 / 2_200,
	},

	["Shark Boss"] = {
		Value = 8.8,
		Rarity = 1 / 3_500,
	},

	MrBossy = {
		Value = 9.2,
		Rarity = 1 / 5_500,
	},

	["Mr Money"] = {
		Value = 9.6,
		Rarity = 1 / 9_000,
	},

	["King Ceo"] = {
		Value = 10,
		Rarity = 1 / 15_000,
	},
}
