return {
	BaseValues = {
		Keyboard = {
			Value = 1,
			Rarity = 500_000_000, -- 1 in 2
		},
		Monitor = {
			Value = 1.5,
			Rarity = 330_000_000, -- 1 in 3
		},
		Computer = {
			Value = 3,
			Rarity = 170_000_000, -- 1 in 5.9
		},
	},
	Variants = {
		Mossy = {
			Value = 4,
			Rarity = 491_700_000, -- 1 in 2
		},

		Wooden = {
			Value = 6,
			Rarity = 258_800_000, -- 1 in 3.9
		},

		Tree = {
			Value = 8,
			Rarity = 129_400_000, -- 1 in 7.7
		},

		Coral = {
			Value = 12,
			Rarity = 64_700_000, -- 1 in 15
		},

		Cloudy = {
			Value = 16,
			Rarity = 30_835_000, -- 1 in 32
		},

		Kitty = {
			Value = 22,
			Rarity = 14_000_000, -- 1 in 71
		},

		Emotional = {
			Value = 30,
			Rarity = 6_090_000, -- 1 in 164
		},

		DigCraft = {
			Value = 40,
			Rarity = 2_650_000, -- 1 in 377
		},

		Tokyo = {
			Value = 55,
			Rarity = 1_100_000, -- 1 in 909
		},

		Steampunk = {
			Value = 75,
			Rarity = 440_000, -- 1 in 2,273
		},

		Witch = {
			Value = 100,
			Rarity = 176_000, -- 1 in 5,682
		},

		Wizzard = {
			Value = 135,
			Rarity = 68_000, -- 1 in 14,706
		},

		Space = {
			Value = 180,
			Rarity = 26_000, -- 1 in 38,462
		},

		Galaxy = {
			Value = 240,
			Rarity = 10_000, -- 1 in 100,000
		},

		Hardcore = {
			Value = 320,
			Rarity = 3_700, -- 1 in 270,270
		},

		Premium = {
			Value = 450,
			Rarity = 1_300, -- 1 in 769,231
		},
	},
}
